// Runtime wiring — REGENERATED BY scripts/deploy.sh ON EVERY DEPLOY. Do not
// hand-edit for branding; that lives in site.config.js.
window.FORUM_CONFIG = {
  apiBase: "/api",
  cognitoDomain: "",        // filled by deploy.sh
  clientId: "",             // filled by deploy.sh
  redirectUri: window.location.origin + "/",
  socialProviders: [],
};
