#!/usr/bin/env bash
# Apply Cognito "Managed Login" branding (logo + colors) derived from the site's
# active theme (web/site.config.js -> web/themes/<theme>.css) so the hosted
# login page matches the site.
# This is NOT managed by CloudFormation (the branding Settings doc is large and
# generated by Cognito), so re-run this after a fresh stack create, or after
# changing theme/logo. Prereqs: stack deployed with ManagedLoginVersion 2 (set
# in template.yaml). Needs awscli + python3 + sips (macOS-only image tooling).
set -euo pipefail
STACK="${STACK:-serverless-forum}"; REGION="${REGION:-us-east-1}"
here="$(cd "$(dirname "$0")/.." && pwd)"; cd "$here"

# Pull LOGO + brand colors out of the active theme's CSS variables.
eval "$(python3 - <<'PY'
import re
cfg = open('web/site.config.js').read()
theme = re.search(r'theme:\s*"([^"]+)"', cfg).group(1)
logo  = re.search(r'logo:\s*"([^"]+)"', cfg).group(1)
css = open(f'web/themes/{theme}.css').read()
v = dict((k, val.strip()) for k, val in re.findall(r'--([a-z0-9-]+):([^;}]+)', css))
def hex8(name):
    val = v[name]
    m = re.fullmatch(r'#([0-9a-fA-F]{6})', val)
    if not m: raise SystemExit(f"theme var --{name} is not a 6-digit hex color: {val}")
    return m.group(1).lower() + 'ff'
print(f'LOGO="web/{logo}"')
print(f'C_PAGE="{hex8("bg")}" C_CARD="{hex8("card")}" C_LINE="{hex8("line")}"')
print(f'C_ACCENT="{hex8("accent")}" C_ACCENT2="{hex8("accent2")}" C_BTN_INK="{hex8("btn-ink")}"')
print(f'PAD_RGB="{v["card"].lstrip("#").upper()}"')
PY
)"
echo "==> logo=$LOGO accent=#$C_ACCENT"

out(){ aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text; }
POOL=$(out UserPoolId); CLIENT=$(out UserPoolClientId)
echo "==> pool=$POOL client=$CLIENT"

# Reuse an existing branding for this client, else create a baseline to modify.
BID=$(aws cognito-idp describe-managed-login-branding-by-client --user-pool-id "$POOL" \
  --client-id "$CLIENT" --region "$REGION" --query "ManagedLoginBranding.ManagedLoginBrandingId" \
  --output text 2>/dev/null || true)
if [ -z "$BID" ] || [ "$BID" = "None" ]; then
  BID=$(aws cognito-idp create-managed-login-branding --user-pool-id "$POOL" --client-id "$CLIENT" \
    --region "$REGION" --use-cognito-provided-values \
    --query "ManagedLoginBranding.ManagedLoginBrandingId" --output text)
fi
echo "==> branding id=$BID"

# Start from Cognito's merged defaults and override just the brand tokens.
aws cognito-idp describe-managed-login-branding --user-pool-id "$POOL" \
  --managed-login-branding-id "$BID" --region "$REGION" --return-merged-resources \
  --query "ManagedLoginBranding.Settings" > /tmp/login_settings.json

C_PAGE="$C_PAGE" C_CARD="$C_CARD" C_LINE="$C_LINE" C_ACCENT="$C_ACCENT" \
C_ACCENT2="$C_ACCENT2" C_BTN_INK="$C_BTN_INK" python3 - <<'PY'
import json, os
d=json.load(open('/tmp/login_settings.json')); c=d['components']
e=os.environ
c['pageBackground']['lightMode']['color']=e['C_PAGE']
c['pageBackground'].setdefault('image',{})['enabled']=False
c['form']['lightMode']['backgroundColor']=e['C_CARD']
c['form']['lightMode']['borderColor']=e['C_LINE']; c['form']['borderRadius']=12.0
c['form']['logo']={'location':'CENTER','position':'TOP','enabled':True,'formInclusion':'IN'}
pb=c['primaryButton']['lightMode']
for st in ('defaults','hover','active'):
    pb[st]['backgroundColor']=e['C_ACCENT'] if st=='defaults' else e['C_ACCENT2']
    pb[st]['textColor']=e['C_BTN_INK']
lk=d['componentClasses'].get('link',{}).get('lightMode',{})
for st in ('defaults','hover'):
    if st in lk and 'textColor' in lk[st]: lk[st]['textColor']=e['C_ACCENT']
json.dump(d,open('/tmp/login_settings.mod.json','w'))
PY

# Managed Login logos must be width:height >= 1:1; normalize to PNG and pad
# square-or-wider on the form's own background color.
TMP_PNG=/tmp/login_logo.png
sips -s format png "$LOGO" --out "$TMP_PNG" >/dev/null 2>&1
H=$(sips -g pixelHeight "$TMP_PNG" | awk '/pixelHeight/{print $2}')
W=$(sips -g pixelWidth  "$TMP_PNG" | awk '/pixelWidth/{print $2}')
if [ "$W" -lt "$H" ]; then W="$H"; fi
sips "$TMP_PNG" --padToHeightWidth "$H" "$W" --padColor "$PAD_RGB" \
  --out /tmp/login_logo_wide.png >/dev/null 2>&1
B64=$(base64 -i /tmp/login_logo_wide.png | tr -d '\n')
python3 - "$B64" <<'PY'
import sys,json
b=sys.argv[1]
json.dump([{"Category":"FORM_LOGO","ColorMode":m,"Extension":"PNG","Bytes":b}
           for m in ("LIGHT","DARK")], open('/tmp/login_assets.json','w'))
PY

aws cognito-idp update-managed-login-branding --user-pool-id "$POOL" \
  --managed-login-branding-id "$BID" --region "$REGION" \
  --settings file:///tmp/login_settings.mod.json --assets file:///tmp/login_assets.json >/dev/null
echo "==> Managed Login branding applied (theme-derived)."
